#!/usr/bin/env bash
CLOUDFLARED_VERSION=$1

if [ -z $CLOUDFLARED_VERSION ]; then
  >&2 echo "No version supplied"
  CLOUDFLARED_VERSION=$(git ls-remote --tags --refs --sort="v:refname" https://github.com/cloudflare/cloudflared | tail -n1 | sed 's/.*\///; s/\^{}//')
  echo "Using latest ${CLOUDFLARED_VERSION}"
fi

docker build --build-arg CLOUDFLARED_VERSION=$CLOUDFLARED_VERSION -t cloudflared_arm_build .
docker run --name cloudflared_arm_build -dt --rm cloudflared_arm_build cat
docker cp $(docker ps -qf "name=cloudflared_arm_build"):/opt/cloudflared-build/out/cloudflared .
docker stop $(docker ps -qf "name=cloudflared_arm_build")
